from enum import Enum


class ReportedAssets(Enum):
    USD = "USD INDEX - ICE FUTURES U.S."
    CAD = "CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE"
    CHF = "SWISS FRANC - CHICAGO MERCANTILE EXCHANGE"
    GBP = "BRITISH POUND - CHICAGO MERCANTILE EXCHANGE"
    JPY = "JAPANESE YEN - CHICAGO MERCANTILE EXCHANGE"
    EUR = "EURO FX - CHICAGO MERCANTILE EXCHANGE"
    AUD = "AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE"
    BTC = "BITCOIN - CHICAGO MERCANTILE EXCHANGE"
    US30 = "DOW JONES U.S. REAL ESTATE IDX - CHICAGO BOARD OF TRADE"
    SPX500 = "E-MINI S&P 500 - CHICAGO MERCANTILE EXCHANGE"
    NDQ100 = "NASDAQ MINI - CHICAGO MERCANTILE EXCHANGE"
    XAU = "GOLD - COMMODITY EXCHANGE INC."
    XAG = "SILVER - COMMODITY EXCHANGE INC."
    XPT = "PLATINUM - NEW YORK MERCANTILE EXCHANGE"

